apiVersion: skaffold/v2beta15
kind: Config
metadata:
  name: http-service
build:
  artifacts:
  - image: http-service
  tagPolicy:
    sha256: {}
deploy:
  kubectl:
    manifests:
    - deployments/*.yaml
